### ISSUE TITLE
Superhintergründe funktionieren nicht bei deutscher Sprache 

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-2.0#4]
Hallo,

bei den Superhintergründen gibt es ein Problem, das bei der deutschen Sprache auftritt, nicht jedoch, wenn Englisch eingestellt ist. Mit deutscher Sprache kann man die meisten Superhintergründe nicht nutzen. Bereits in der Auswahl bzw. je nach Hintergrund in der Auswahl des Landepunktes ist nur ein schwarzer Bildschirm zu sehen. Wählt man den Hintergrund dennoch, funktioniert er nicht.
Auf Englisch funktioniert alles reibungslos.

Das Problem tritt bei mir auf seit OS1.0.47.0.UNCCNXM (houji). Ich vermute aber eher, dass dies mit dem Update der APKs der Superhintergründe zu tun hat, da kurz vor Release der ROM die APKs geupdatet wurden (28.09.2024).

Könnt ihr hier irgendwie helfen?

**Comment by MeiGuddet** [comment]
Die Superhintergründe gehören schon seit langem nicht mehr zu Übersetzung dazu. Bisher wurden die alten Dateien für Earth und Mars noch mitgeschleppt. Die hab ich jetzt mal aus den Repos HyperOS 1.0 + 2.0 gelöscht. Vielleicht bringt's ja was.

**Comment by darki15** [comment]
Mit dem heutigen ROM Update hat sich leider nichts geändert. Auf Englisch funktionieren alle Superhintergründe, auf Deutsch nicht.
Danke trotzdem für den Versuch!
